version: '3'
services:
  product-service:
    build: ./Product.Service
    container_name: product-service
    ports:
    - "5000:80"
    environment: 
    - MongoDbConnectionString=mongodb://mongo-product-service:27017
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - AWS_REGION=$AWS_REGION
    depends_on: 
    - mongo-product-service

  cart-service:
    build: ./Cart.Service
    container_name: cart-service
    ports:
    - "5050:80"
    environment: 
    - MongoDbConnectionString=mongodb://mongo-cart-service:27017
    - ProductServiceURI=http://product-service
    - AmazonSQSCheckoutQueueURL=https://sqs.us-east-1.amazonaws.com/105029661252/hackati-marketplace-start-checkout
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - AWS_REGION=$AWS_REGION
    depends_on: 
    - mongo-cart-service
    - product-service
  
  checkout-service:
    build: ./Checkout.Service
    container_name: checkout-service
    ports:
    - 8080:8080
    environment: 
    - MongoDbConnectionString=mongodb://mongo-checkout-service:27017
    - AmazonSQSCheckoutQueueURL=https://sqs.us-east-1.amazonaws.com/105029661252/hackati-marketplace-start-checkout
    - PrometheusPort=8080
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - AWS_REGION=$AWS_REGION
    depends_on: 
    - mongo-checkout-service
    - product-service

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090

  mongo-product-service:
    image: mongo
    container_name: mongo-product-service

  mongo-cart-service:
    image: mongo
    container_name: mongo-cart-service

  mongo-checkout-service:
    image: mongo
    container_name: mongo-checkout-service

