version: '3'
services:
  product-service:
    build: ./Product.Service
    ports:
    - "5000:80"
    environment: 
    - MongoDbConnectionString=mongodb://mongo-product-service:27017
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    depends_on: 
    - mongo-product-service
  mongo-product-service:
    image: mongo
    container_name: "mongo-product-service"
